[package]
name = "bevy_stutter"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8", default-features = false, features = ["render"] }
fastrand = "1.8"
instant = "0.1.12" # best to match bevy version

[dev-dependencies]
bevy = "0.8"